# POST http://localhost:3001/api/blogs HTTP/1.1
# Content-Type: application/json

# {
#   "title": "Reverend instanity",
#   "author": "Gu Zhen Ren",
#   "url": "https://www.webnovel.com/book/7996858406002505/Reverend-Insanity",
#   "likes": 1234
# }


#DELETE  http://localhost:3001/api/blogs/5d611eff3deff829ccf25a2f HTTP/1.1

PUT  http://localhost:3001/api/blogs/5d611f8edf54cb7fb8d2e421 HTTP/1.1
Content-Type: application/json

{
  "title": "Reverend instanity",
  "author": "Gu Zhen Ren",
  "url": "https://www.webnovel.com/book/7996858406002505/Reverend-Insanity",
  "likes": 1111111111111111
}