# POST http://localhost:3001/api/blogs HTTP/1.1
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IndldyIsImlkIjoiNWQ2MmEwNDE1MGUxNjMxNDhjMzk0ZTk3IiwiaWF0IjoxNTY2NzQ0NjUzfQ.5dMc5dvCalXSUUUGoYEhhVb9iQXTxjjfYKXguHVMY7I

# {
#   "title": "Reverend instanity",
#   "author": "Gu Zhen Ren",
#   "url": "https://www.webnovel.com/book/7996858406002505/Reverend-Insanity",
#   "likes": 1234
# }


DELETE  http://localhost:3001/api/blogs/5d62a114144acc27c0668228 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Indld3ciLCJpZCI6IjVkNjJhNjY5MjliNTYwM2MyYzYyZDQzMiIsImlhdCI6MTU2Njc0NzYyOX0.N1LqSg8sJItRNdtDdOHhUdIffyg2Xvkf5ZYxOsgPeWI
# PUT  http://localhost:3001/api/blogs/5d611f8edf54cb7fb8d2e421 HTTP/1.1
# Content-Type: application/json

# {
#   "title": "Reverend instanity",
#   "author": "Gu Zhen Ren",
#   "url": "https://www.webnovel.com/book/7996858406002505/Reverend-Insanity",
#   "likes": 1111111111111111
# }